### ISSUE TITLE
Mac Instillation 

### ISSUE THREAD

**Issue by rezah** [kahypar/kahypar#103]
I am trying to install KaHyPar on Mac: pip install KaHyPar. But getting the following error; I appreciate any help

pip install kahypar
Collecting kahypar
  Using cached kahypar-1.0.tar.gz (8.0 MB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: kahypar
  Building wheel for kahypar (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [46 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Traceback (most recent call last):
        File "/private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-install-1buzos80/kahypar_41bddcb4ee774feaa882df54efee8756/setup.py", line 20, in run
          out = subprocess.check_output(['cmake', '--version'])
        File "/Users/rezah/opt/anaconda3/lib/python3.9/subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/Users/rezah/opt/anaconda3/lib/python3.9/subprocess.py", line 505, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/Users/rezah/opt/anaconda3/lib/python3.9/subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/Users/rezah/opt/anaconda3/lib/python3.9/subprocess.py", line 1821, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'cmake'
      
      During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-install-1buzos80/kahypar_41bddcb4ee774feaa882df54efee8756/setup.py", line 74, in <module>
          setup(
        File "/Users/rezah/opt/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/Users/rezah/opt/anaconda3/lib/python3.9/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/Users/rezah/opt/anaconda3/lib/python3.9/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/Users/rezah/opt/anaconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Users/rezah/opt/anaconda3/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/Users/rezah/opt/anaconda3/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Users/rezah/opt/anaconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Users/rezah/opt/anaconda3/lib/python3.9/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/Users/rezah/opt/anaconda3/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Users/rezah/opt/anaconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-install-1buzos80/kahypar_41bddcb4ee774feaa882df54efee8756/setup.py", line 22, in run
          raise RuntimeError("CMake must be installed to build the following extensions: " +
      RuntimeError: CMake must be installed to build the following extensions: kahypar
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for kahypar
  Running setup.py clean for kahypar
Failed to build kahypar
Installing collected packages: kahypar
  Running setup.py install for kahypar ... error
  error: subprocess-exited-with-error

**Comment by SebastianSchlag** [comment]
`RuntimeError: CMake must be installed to build the following extensions: kahypar`

This sounds like you are missing `CMake`. Did you install cmake (e.g. via homebrew: https://formulae.brew.sh/formula/cmake)?

**Comment by rezah** [comment]
Thanks fir comment; I did install make but getting this error:

**Comment by rezah** [comment]
Collecting KaHyPar
  Using cached kahypar-1.0.tar.gz (8.0 MB)
Building wheels for collected packages: KaHyPar
  Building wheel for KaHyPar (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/rezah/opt/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-install-1vl1z9_a/kahypar_cbe421de3f9047ada00a322fdcf993e4/setup.py'"'"'; __file__='"'"'/private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-install-1vl1z9_a/kahypar_cbe421de3f9047ada00a322fdcf993e4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-wheel-ty4k42bq
       cwd: /private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-install-1vl1z9_a/kahypar_cbe421de3f9047ada00a322fdcf993e4/
  Complete output (91 lines):
  running bdist_wheel
  running build
  running build_ext
  -- The CXX compiler identification is AppleClang 13.0.0.13000029
  -- The C compiler identification is AppleClang 13.0.0.13000029
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
  -- Found Threads: TRUE
  -- Found Threads:
  CMake Deprecation Warning at external_tools/googletest/CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.
  
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  
  
  CMake Deprecation Warning at external_tools/googletest/googlemock/CMakeLists.txt:41 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.
  
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  
  
  CMake Deprecation Warning at external_tools/googletest/googletest/CMakeLists.txt:48 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.
  
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  
  
  -- Found PythonInterp: /Users/rezah/opt/anaconda3/bin/python (found version "3.9.7")
  -- Found Python: /Users/rezah/opt/anaconda3/bin/python3.9 (found version "3.9.7") found components: Interpreter
  -- Found PythonLibs: /Users/rezah/opt/anaconda3/lib/libpython3.9.dylib (found version "3.9.7")
  CMake Error at /opt/homebrew/Cellar/cmake/3.22.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find Boost (missing: Boost_INCLUDE_DIR program_options) (Required
    is at least version "1.48.0")
  Call Stack (most recent call first):
    /opt/homebrew/Cellar/cmake/3.22.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
    /opt/homebrew/Cellar/cmake/3.22.2/share/cmake/Modules/FindBoost.cmake:2375 (find_package_handle_standard_args)
    CMakeLists.txt:142 (find_package)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-install-1vl1z9_a/kahypar_cbe421de3f9047ada00a322fdcf993e4/build/temp.macosx-10.9-x86_64-3.9/CMakeFiles/CMakeOutput.log".
  See also "/private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-install-1vl1z9_a/kahypar_cbe421de3f9047ada00a322fdcf993e4/build/temp.macosx-10.9-x86_64-3.9/CMakeFiles/CMakeError.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-install-1vl1z9_a/kahypar_cbe421de3f9047ada00a322fdcf993e4/setup.py", line 74, in <module>
      setup(
    File "/Users/rezah/opt/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/Users/rezah/opt/anaconda3/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Users/rezah/opt/anaconda3/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/Users/rezah/opt/anaconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/rezah/opt/anaconda3/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/Users/rezah/opt/anaconda3/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/rezah/opt/anaconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/rezah/opt/anaconda3/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Users/rezah/opt/anaconda3/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/rezah/opt/anaconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-install-1vl1z9_a/kahypar_cbe421de3f9047ada00a322fdcf993e4/setup.py", line 31, in run
      self.build_extension(ext)
    File "/private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-install-1vl1z9_a/kahypar_cbe421de3f9047ada00a322fdcf993e4/setup.py", line 58, in build_extension
      subprocess.check_call(
    File "/Users/rezah/opt/anaconda3/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-install-1vl1z9_a/kahypar_cbe421de3f9047ada00a322fdcf993e4', '-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-install-1vl1z9_a/kahypar_cbe421de3f9047ada00a322fdcf993e4/build/lib.macosx-10.9-x86_64-3.9', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-install-1vl1z9_a/kahypar_cbe421de3f9047ada00a322fdcf993e4/build/lib.macosx-10.9-x86_64-3.9', '-DBOOST_ROOT=/software/boost_1_66_0', '-DPYTHON_EXECUTABLE=/Users/rezah/opt/anaconda3/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for KaHyPar
  Running setup.py clean for KaHyPar
Failed to build KaHyPar
Installing collected packages: KaHyPar
    Running setup.py install for KaHyPar ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/rezah/opt/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-install-1vl1z9_a/kahypar_cbe421de3f9047ada00a322fdcf993e4/setup.py'"'"'; __file__='"'"'/private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-install-1vl1z9_a/kahypar_cbe421de3f9047ada00a322fdcf993e4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-record-4tixrlsp/install-record.txt --single-version-externally-managed --compile --install-headers /Users/rezah/opt/anaconda3/include/python3.9/KaHyPar
         cwd: /private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-install-1vl1z9_a/kahypar_cbe421de3f9047ada00a322fdcf993e4/
    Complete output (93 lines):
    running install
    running build
    running build_ext
    -- The CXX compiler identification is AppleClang 13.0.0.13000029
    -- The C compiler identification is AppleClang 13.0.0.13000029
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
    -- Found Threads: TRUE
    -- Found Threads:
    CMake Deprecation Warning at external_tools/googletest/CMakeLists.txt:1 (cmake_minimum_required):
      Compatibility with CMake < 2.8.12 will be removed from a future version of
      CMake.
    
      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.
    
    
    CMake Deprecation Warning at external_tools/googletest/googlemock/CMakeLists.txt:41 (cmake_minimum_required):
      Compatibility with CMake < 2.8.12 will be removed from a future version of
      CMake.
    
      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.
    
    
    CMake Deprecation Warning at external_tools/googletest/googletest/CMakeLists.txt:48 (cmake_minimum_required):
      Compatibility with CMake < 2.8.12 will be removed from a future version of
      CMake.
    
      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.
    
    
    -- Found PythonInterp: /Users/rezah/opt/anaconda3/bin/python (found version "3.9.7")
    -- Found Python: /Users/rezah/opt/anaconda3/bin/python3.9 (found version "3.9.7") found components: Interpreter
    -- Found PythonLibs: /Users/rezah/opt/anaconda3/lib/libpython3.9.dylib (found version "3.9.7")
    CMake Error at /opt/homebrew/Cellar/cmake/3.22.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
      Could NOT find Boost (missing: Boost_INCLUDE_DIR program_options) (Required
      is at least version "1.48.0")
    Call Stack (most recent call first):
      /opt/homebrew/Cellar/cmake/3.22.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
      /opt/homebrew/Cellar/cmake/3.22.2/share/cmake/Modules/FindBoost.cmake:2375 (find_package_handle_standard_args)
      CMakeLists.txt:142 (find_package)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-install-1vl1z9_a/kahypar_cbe421de3f9047ada00a322fdcf993e4/build/temp.macosx-10.9-x86_64-3.9/CMakeFiles/CMakeOutput.log".
    See also "/private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-install-1vl1z9_a/kahypar_cbe421de3f9047ada00a322fdcf993e4/build/temp.macosx-10.9-x86_64-3.9/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-install-1vl1z9_a/kahypar_cbe421de3f9047ada00a322fdcf993e4/setup.py", line 74, in <module>
        setup(
      File "/Users/rezah/opt/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/Users/rezah/opt/anaconda3/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/rezah/opt/anaconda3/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Users/rezah/opt/anaconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/rezah/opt/anaconda3/lib/python3.9/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Users/rezah/opt/anaconda3/lib/python3.9/distutils/command/install.py", line 546, in run
        self.run_command('build')
      File "/Users/rezah/opt/anaconda3/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/rezah/opt/anaconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/rezah/opt/anaconda3/lib/python3.9/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Users/rezah/opt/anaconda3/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/rezah/opt/anaconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-install-1vl1z9_a/kahypar_cbe421de3f9047ada00a322fdcf993e4/setup.py", line 31, in run
        self.build_extension(ext)
      File "/private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-install-1vl1z9_a/kahypar_cbe421de3f9047ada00a322fdcf993e4/setup.py", line 58, in build_extension
        subprocess.check_call(
      File "/Users/rezah/opt/anaconda3/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-install-1vl1z9_a/kahypar_cbe421de3f9047ada00a322fdcf993e4', '-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-install-1vl1z9_a/kahypar_cbe421de3f9047ada00a322fdcf993e4/build/lib.macosx-10.9-x86_64-3.9', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-install-1vl1z9_a/kahypar_cbe421de3f9047ada00a322fdcf993e4/build/lib.macosx-10.9-x86_64-3.9', '-DBOOST_ROOT=/software/boost_1_66_0', '-DPYTHON_EXECUTABLE=/Users/rezah/opt/anaconda3/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/rezah/opt/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-install-1vl1z9_a/kahypar_cbe421de3f9047ada00a322fdcf993e4/setup.py'"'"'; __file__='"'"'/private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-install-1vl1z9_a/kahypar_cbe421de3f9047ada00a322fdcf993e4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/zv/sxj_wv191mgg0_1j8tskyx6r0000gn/T/pip-record-4tixrlsp/install-record.txt --single-version-externally-managed --compile --install-headers /Users/rezah/opt/anaconda3/include/python3.9/KaHyPar Check the logs for full command output.
(base) rezah@Rezas-iMac TN-circuit %

**Comment by SebastianSchlag** [comment]
This indicates that you did not install `boost`. Please install boost via hombrew (see https://formulae.brew.sh/formula/boost) or download and install the latest boost version from source (https://www.boost.org).

**Comment by SebastianSchlag** [comment]
Hey @rezah,
just checking in. Were you able to compile KaHyPar after installing boost?

**Comment by rezah** [comment]
Thanks for asking. I was able to install it.  But I think I am getting an error while running that: I really appreciate if you can help me to debug that 


Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/rezah/opt/anaconda3/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/rezah/opt/anaconda3/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/rezah/opt/anaconda3/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/rezah/opt/anaconda3/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/rezah/opt/anaconda3/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/rezah/opt/anaconda3/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/rezah/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/rezah/Dropbox/Prog/TN-circuit/tn.py", line 50, in <module>
    print("E_init=", quf.energy_f_qmera(tn_U, list_inter, **dic))
  File "/Users/rezah/Dropbox/Prog/TN-circuit/quf.py", line 331, in energy_f_qmera
    return sum(
  File "/Users/rezah/Dropbox/Prog/TN-circuit/quf.py", line 332, in <genexpr>
    local_expectation_mera(ttn, list_inter,iter, **kwargs)
  File "/Users/rezah/Dropbox/Prog/TN-circuit/quf.py", line 324, in local_expectation_mera
    E=mera_ij_ex.contract(all, optimize=kwargs['optimize'])
  File "/Users/rezah/quimb/quimb/tensor/tensor_core.py", line 6799, in contract
    return tensor_contract(*self, **opts)
  File "/Users/rezah/quimb/quimb/tensor/tensor_core.py", line 577, in tensor_contract
    expression = get_contraction(eq, *shapes, **contract_opts)
  File "/Users/rezah/quimb/quimb/tensor/tensor_core.py", line 251, in get_contraction
    return _get_contraction(eq, shapes, optimize, cache, get, **kwargs)
  File "/Users/rezah/quimb/quimb/tensor/tensor_core.py", line 208, in _get_contraction
    path = path_fn(eq, *shapes, optimize=optimize, **kwargs)
  File "/Users/rezah/quimb/quimb/tensor/tensor_core.py", line 129, in _get_contract_path
    path = optimize(inputs, output, size_dict, **kwargs)
  File "/Users/rezah/cotengra/cotengra/hyper.py", line 781, in __call__
    self._cache[h] = self._compute_path(inputs, output, size_dict)
  File "/Users/rezah/cotengra/cotengra/hyper.py", line 755, in _compute_path
    self._opt._search(inputs, output, size_dict)
  File "/Users/rezah/cotengra/cotengra/hyper.py", line 557, in _search
    for trial in trials:
  File "/Users/rezah/opt/anaconda3/lib/python3.9/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/Users/rezah/cotengra/cotengra/hyper.py", line 496, in _gen_results_parallel
    future = submit(
  File "/Users/rezah/cotengra/cotengra/parallel.py", line 156, in submit
    return pool.submit(fn, *args, **kwargs)
  File "/Users/rezah/opt/anaconda3/lib/python3.9/concurrent/futures/process.py", line 697, in submit
    self._adjust_process_count()
  File "/Users/rezah/opt/anaconda3/lib/python3.9/concurrent/futures/process.py", line 675, in _adjust_process_count
    p.start()
  File "/Users/rezah/opt/anaconda3/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/rezah/opt/anaconda3/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/rezah/opt/anaconda3/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/rezah/opt/anaconda3/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/rezah/opt/anaconda3/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/rezah/opt/anaconda3/lib/python3.9/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/rezah/opt/anaconda3/lib/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
log2[SIZE]: inf log10[FLOPs]: inf:   0%|                                  | 0/128 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "/Users/rezah/Dropbox/Prog/TN-circuit/tn.py", line 50, in <module>
    print("E_init=", quf.energy_f_qmera(tn_U, list_inter, **dic))
  File "/Users/rezah/Dropbox/Prog/TN-circuit/quf.py", line 331, in energy_f_qmera
    return sum(
  File "/Users/rezah/Dropbox/Prog/TN-circuit/quf.py", line 332, in <genexpr>
    local_expectation_mera(ttn, list_inter,iter, **kwargs)
  File "/Users/rezah/Dropbox/Prog/TN-circuit/quf.py", line 324, in local_expectation_mera
    E=mera_ij_ex.contract(all, optimize=kwargs['optimize'])
  File "/Users/rezah/quimb/quimb/tensor/tensor_core.py", line 6799, in contract
    return tensor_contract(*self, **opts)
  File "/Users/rezah/quimb/quimb/tensor/tensor_core.py", line 577, in tensor_contract
    expression = get_contraction(eq, *shapes, **contract_opts)
  File "/Users/rezah/quimb/quimb/tensor/tensor_core.py", line 251, in get_contraction
    return _get_contraction(eq, shapes, optimize, cache, get, **kwargs)
  File "/Users/rezah/quimb/quimb/tensor/tensor_core.py", line 208, in _get_contraction
    path = path_fn(eq, *shapes, optimize=optimize, **kwargs)
  File "/Users/rezah/quimb/quimb/tensor/tensor_core.py", line 129, in _get_contract_path
    path = optimize(inputs, output, size_dict, **kwargs)
  File "/Users/rezah/cotengra/cotengra/hyper.py", line 781, in __call__
    self._cache[h] = self._compute_path(inputs, output, size_dict)
  File "/Users/rezah/cotengra/cotengra/hyper.py", line 755, in _compute_path
    self._opt._search(inputs, output, size_dict)
  File "/Users/rezah/cotengra/cotengra/hyper.py", line 557, in _search
    for trial in trials:
  File "/Users/rezah/opt/anaconda3/lib/python3.9/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/Users/rezah/cotengra/cotengra/hyper.py", line 502, in _gen_results_parallel
    yield self._get_and_report_next_future()
  File "/Users/rezah/cotengra/cotengra/hyper.py", line 483, in _get_and_report_next_future
    trial = future.result()
  File "/Users/rezah/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/Users/rezah/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

**Comment by SebastianSchlag** [comment]
Oh. This looks like a `cotengra` related issue. Did you try reaching out to the folks over at https://github.com/jcmgray/cotengra ?

**Comment by shadibeh** [comment]
Hi @rezah,
I have the same problem with installing Kahypar on my Mac.
Would you please let me know if you could find a solution for it.

Thanks

**Comment by SebastianSchlag** [comment]
Hi @shadibeh, have you tried getting in touch with the `contegra` developers? From the logs that @rezah posted, I can't really see whether this is an issue with KaHyPar.

**Comment by rezah** [comment]
@shadibeh, I was not able to resolve it, but you can check with Johnnie the owner of cotengra

**Comment by SebastianSchlag** [comment]
@shadibeh If you open up an issue in the contegra repo, could you please link it to this thread for future reference?
