### ISSUE TITLE
python 3.11 pypi build

### ISSUE THREAD

**Issue by jcmgray** [kahypar/kahypar#163]
This is just a gentle enquiry about (/ request for), a cpython 3.11 `kahypar` pypi build.

**Comment by SebastianSchlag** [comment]
Hey @jcmgray, let me see what I can do. This should be possible somehow.

**Comment by SebastianSchlag** [comment]
I just gave it a try, but it seems like there are some `pybind`-related issues with 3.11:

```
 /kahypar/python/pybind11/include/pybind11/cast.h:442:36: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
    442 |                 "  " + handle(frame->f_code->co_filename).cast<std::string>() +
        |                                    ^~
  compilation terminated due to -Wfatal-errors.
  gmake[3]: *** [python/CMakeFiles/kahypar_python.dir/build.make:80: python/CMakeFiles/kahypar_python.dir/module.cpp.o] Error 1
  gmake[2]: *** [CMakeFiles/Makefile2:3774: python/CMakeFiles/kahypar_python.dir/all] Error 2
  gmake[1]: *** [CMakeFiles/Makefile2:3781: python/CMakeFiles/kahypar_python.dir/rule] Error 2
  gmake: *** [Makefile:1648: kahypar_python] Error 2
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/kahypar/setup.py", line 80, in <module>
      setup(
    File "/opt/_internal/cpython-3.11.3/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/_internal/cpython-3.11.3/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "/opt/_internal/cpython-3.11.3/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/opt/_internal/cpython-3.11.3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/opt/_internal/cpython-3.11.3/lib/python3.11/site-packages/setuptools/dist.py", line 1244, in run_command
      super().run_command(command)
    File "/opt/_internal/cpython-3.11.3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/opt/_internal/cpython-3.11.3/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 343, in run
      self.run_command("build")
    File "/opt/_internal/cpython-3.11.3/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "/opt/_internal/cpython-3.11.3/lib/python3.11/site-packages/setuptools/dist.py", line 1244, in run_command
      super().run_command(command)
    File "/opt/_internal/cpython-3.11.3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/opt/_internal/cpython-3.11.3/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
      self.run_command(cmd_name)
    File "/opt/_internal/cpython-3.11.3/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "/opt/_internal/cpython-3.11.3/lib/python3.11/site-packages/setuptools/dist.py", line 1244, in run_command
      super().run_command(command)
    File "/opt/_internal/cpython-3.11.3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/kahypar/setup.py", line 32, in run
      self.build_extension(ext)
    File "/kahypar/setup.py", line 67, in build_extension
      subprocess.check_call(
    File "/opt/_internal/cpython-3.11.3/lib/python3.11/subprocess.py", line 413, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'kahypar_python', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
  error: subprocess-exited-with-error
```

If I find some time in the next couple of weeks, I'll dig a bit deeper.

**Comment by jcmgray** [comment]
Ah thanks for checking, I see it is not as simple as just adding to a build matrix somewhere. From a brief look it appears that pybind >= 2.10.1 is required for py3.11 support. 

I did try manually updating the pybind submodule and I can almost compile from source on python 3.11, but I get this linking error at the end:
```
/usr/bin/ld: ../libmini_boost.a(cmdline.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTVN5boost15program_options26invalid_command_line_styleE' can not be used when making a shared object; recompile with -fPIC
```

**Comment by SebastianSchlag** [comment]
Thanks for checking @jcmgray. I hopefully have some spare cycles in the next couple of weeks to try this myself.

**Comment by emprice** [comment]
Thinking about it some more, the problem may be on [this line](https://github.com/kahypar/kahypar/blob/a0b83cafdfe6dfc8900f044f39659754a51f3a97/CMakeLists.txt#L196) in the CMake config. The minimal Boost build will always be static, and I think that's the problem @jcmgray runs into at the final link step. The solution might be as simple as changing `STATIC` to `SHARED`, or just let the user control the option by not specifying anything in the config, so it will default to using the `BUILD_SHARED_LIBS` user option.

**Comment by jcmgray** [comment]
Thanks for looking into more @emprice, good to know it can work with only small changes!

I suppose my main interest is having the pypi wheel accessible for easy installation. I wonder @SebastianSchlag if you have thought about a github action that builds and pushes to pypi.org in a automated and repeatable fashion?

**Comment by SebastianSchlag** [comment]
Thank you very much for our investigation @emprice. I was able to build a version for Python 3.11 and uploaded it to pypi: https://files.pythonhosted.org/packages/66/3a/d90e615278d82e20ecb5d5f46e5e9e475de347850619c40468fcce7719e5/kahypar-1.3.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

@jcmgray  Yeah, I have actually thought about that. I just haven't had the time to actually sit down and get that to work. :)

**Comment by jcmgray** [comment]
Re py311 version - nice, thanks! And yes fully understand about scarcity of time to setup these things...
